name = "General MIDI"

[notes]
21 = "HH Splash"
23 = "HH Half-Open"
35 = "Bass Drum 2"
36 = "Kick"
37 = "Side Stick"
38 = "Snare"
39 = "Hand Clap"
40 = "Snare Rim"
41 = "Low Floor Tom"
42 = "Closed Hi-Hat"
43 = "High Floor Tom"
44 = "Pedal Hi-Hat"
45 = "Low Tom"
46 = "Open Hi-Hat"
47 = "Low-Mid Tom"
48 = "Hi-Mid Tom"
49 = "Crash 1"
50 = "High Tom"
51 = "Ride"
52 = "Chinese Cymbal"
53 = "Ride Bell"
54 = "Tambourine"
55 = "Splash Cymbal"
56 = "Cowbell"
57 = "Crash 2"
58 = "Vibraslap"
59 = "Ride 2"

[chokes]
42 = [46, 23, 21]
44 = [46, 23, 21]
23 = [46]
